site_name: Analytics Wiki
site_description: Конспекты и материалы по аналитике данных
site_author: Евгений Каламагин

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  font: false

plugins:
  - search:
      lang: ru

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
